"""Public Chat Kit API."""

from .runtime import append_user_message, ensure_session_state, stream_assistant_turn, stream_chat_turn
from .tools import (
    DEFAULT_HEIGHTS,
    PREBUILT_COMPONENT_HEIGHTS,
    SYSTEM_PROMPT,
    build_chat_completions_tools,
    build_responses_tools,
    build_system_prompt,
    element_from_tool_call,
    execute_tool_call,
    parse_tool_arguments,
    register_tool_executor,
    render_element,
)
from .types import (
    AssistantChunk,
    ChatBackendConfig,
    ChatEvent,
    ChatMessage,
    StreamingSessionState,
    ToolCallCard,
    ToolCallEventState,
    append_event,
    create_session_state,
    make_event,
    replay_timeline,
)
from .ui import (
    chat_container,
    chat_message,
    chat_reasoning,
    chat_stream,
    chat_tool_card,
    register_tool_card_renderer,
    render_chat_message,
    render_chat_session,
)

__all__ = [
    "AssistantChunk",
    "ChatBackendConfig",
    "ChatEvent",
    "ChatMessage",
    "StreamingSessionState",
    "ToolCallCard",
    "ToolCallEventState",
    "SYSTEM_PROMPT",
    "DEFAULT_HEIGHTS",
    "PREBUILT_COMPONENT_HEIGHTS",
    "append_event",
    "append_user_message",
    "build_chat_completions_tools",
    "build_responses_tools",
    "build_system_prompt",
    "chat_container",
    "chat_message",
    "chat_reasoning",
    "chat_stream",
    "chat_tool_card",
    "create_session_state",
    "element_from_tool_call",
    "ensure_session_state",
    "execute_tool_call",
    "make_event",
    "parse_tool_arguments",
    "register_tool_card_renderer",
    "register_tool_executor",
    "render_chat_message",
    "render_chat_session",
    "render_element",
    "replay_timeline",
    "stream_assistant_turn",
    "stream_chat_turn",
]
